# Schema for the configuration files of the getresponse_forms module.

getresponse_forms.getresponse_forms.*:
  type: config_entity
  label: 'Getresponse Forms config'
  mapping:
    id:
      type: string
      label: 'Machine Name'
    title:
      type: text
      label: 'Title'
    uuid:
      type: string
      label: 'UUID'
    gr_lists:
      type: sequence
      label: 'GetResponse List(s)'
    mode:
      type: int
      label: 'Mode'
    description:
      type: text
      label: 'Description'
    send_welcome:
      type: boolean
      label: 'Send Welcome'
    include_interest_groups:
      type: boolean
      label: 'Include Interest Groups'
    status:
      type: boolean
      label: 'Status'
    path:
      type: string
      label: 'Path'
    submit_button:
      type: text
      label: 'Submit Button'
    confirmation_message:
      type: text
      label: 'Confirmation Message'
    destination:
      type: string
      label: 'Destination'
